---
- hosts:
    - bastion.sea1.wobscale.website
  become: yes
  become_method: sudo
  tasks:
    - copy: src=files/sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644
    - copy: src=files/interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
