---
- hosts:
    - edge.sea1.wobscale.website
  become: yes
  become_method: doas
  tasks:
    - openbsd_pkg: name={{ item }} state=latest
      with_items:
        - bash
        - curl
        - python
        - screen
        - vim--no_x11
